apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ddos-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: ddos-config-secrets
    creationPolicy: Owner
  data:
  {{- range $key, $path := .Values.secrets.ssm }}
  - secretKeyRef:
      name: {{ $key }}
      key: {{ $key | replace "_" "-" }}
    remoteRef:
      key: {{ $path }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: ecr-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"auth\":\"%s\"}}}" (include "ecr.registry" .) (include "ecr.auth" .) | b64enc | quote }}

{{- define "ecr.registry" -}}
{{ .Values.global.ecrRepository | default (printf "%s.dkr.ecr.%s.amazonaws.com" .Values.aws.accountId .Values.aws.region) }}
{{- end }}

{{- define "ecr.auth" -}}
{{ .Values.global.ecrAuth | default "BASE64_AWS_CREDS" | b64enc }}
{{- end }}
