"""
Threshold-Based Detector

Detects DDoS attacks using static and dynamic thresholds.
"""

import time
import math
from collections import deque
from enum import Enum
from dataclasses import dataclass, field
from typing import Dict, Any, Optional, List, Tuple, Deque
import logging

logger = logging.getLogger(__name__)


class AttackType(Enum):
    """Types of DDoS attacks that can be detected"""
    NONE = "none"
    SYN_FLOOD = "syn_flood"
    UDP_FLOOD = "udp_flood"
    ICMP_FLOOD = "icmp_flood"
    HTTP_FLOOD = "http_flood"
    PPS_FLOOD = "pps_flood"
    BANDWIDTH_FLOOD = "bandwidth_flood"
    DISTRIBUTED_ENTROPY = "distributed_entropy"


@dataclass
class ThresholdConfig:
    """Configuration for threshold-based detection"""
    packets_per_second_threshold: int = 10000
    bytes_per_second_threshold: int = 100_000_000
    flows_per_second_threshold: int = 5000
    packets_per_second_per_ip: int = 5000
    connections_per_second_per_ip: int = 1000
    entropy_src_ip_threshold: float = 0.7
    syn_flood_syn_ratio: float = 0.8
    syn_flood_min_rate: int = 5000
    udp_flood_ratio: float = 0.7
    udp_flood_min_rate: int = 10000
    icmp_flood_ratio: float = 0.5
    icmp_flood_min_rate: int = 5000
    enable_dynamic_thresholds: bool = True
    dynamic_window_size: int = 60
    dynamic_threshold_multiplier: float = 3.0
    alert_cooldown_seconds: int = 30
    min_window_seconds: int = 5
    max_tracked_ips: int = 100_000


@dataclass
class ThresholdAlert:
    """Alert generated by threshold detector"""
    attack_type: AttackType
    severity: str
    confidence: float
    timestamp: float
    window_size: int
    current_value: float
    threshold_value: float
    affected_ips: List[str]
    details: Dict[str, Any]

    def to_dict(self) -> Dict[str, Any]:
        """Convert alert to dictionary"""
        return {
            'attack_type': self.attack_type.value,
            'severity': self.severity,
            'confidence': self.confidence,
            'timestamp': self.timestamp,
            'window_size': self.window_size,
            'current_value': self.current_value,
            'threshold_value': self.threshold_value,
            'affected_ips': self.affected_ips[:10],
            'details': self.details,
            'detector': 'threshold',
        }


class ThresholdDetector:
    """Detects DDoS attacks using threshold-based rules"""
    
    def __init__(self, config: Optional[ThresholdConfig] = None):
        self.config = config or ThresholdConfig()
        self.history_packets: Deque[float] = deque(maxlen=self.config.dynamic_window_size)
        self.history_bytes: Deque[float] = deque(maxlen=self.config.dynamic_window_size)
        self.history_entropy: Deque[float] = deque(maxlen=self.config.dynamic_window_size)
        self.last_alert_time: Dict[str, float] = {}
        self.ip_packet_counts: Dict[str, Deque[float]] = {}
        self.alert_history: Deque = deque(maxlen=1000)
        logger.info("ThresholdDetector initialized")

    def _is_in_cooldown(self, attack_key: str) -> bool:
        """Check if attack type is in cooldown period"""
        if attack_key not in self.last_alert_time:
            return False
        return time.time() - self.last_alert_time[attack_key] < self.config.alert_cooldown_seconds

    def _update_cooldown(self, attack_key: str):
        """Update cooldown timestamp for attack type"""
        self.last_alert_time[attack_key] = time.time()

    def _get_dynamic_threshold(self, history: Deque[float], default_threshold: float, direction: str = "upper") -> float:
        """Calculate dynamic threshold based on historical data"""
        if not self.config.enable_dynamic_thresholds or len(history) < 10:
            return default_threshold

        values = list(history)
        mean = sum(values) / len(values)
        variance = sum((x - mean) ** 2 for x in values) / len(values)
        std = math.sqrt(variance) if variance > 0 else 0

        if direction == "lower":
            dynamic = mean - (self.config.dynamic_threshold_multiplier * std)
            return max(0.0, min(dynamic, default_threshold))

        dynamic = mean + (self.config.dynamic_threshold_multiplier * std)
        return max(dynamic, default_threshold)

    def _get_top_ip_addresses(self, ip_counts: List[Tuple[str, int]], limit: int = 5) -> List[str]:
        """Get top IP addresses from counts"""
        return [ip for ip, _ in ip_counts[:limit]]

    def detect_volumetric(self, features, current_time: float) -> Optional[ThresholdAlert]:
        """Detect volumetric DDoS attacks (high PPS/BPS)"""
        self.history_packets.append(features.packets_per_second)
        self.history_bytes.append(features.bytes_per_second)

        # Check PPS threshold
        if features.packets_per_second > self.config.packets_per_second_threshold:
            dynamic_threshold = self._get_dynamic_threshold(
                self.history_packets, self.config.packets_per_second_threshold, "upper"
            )

            if features.packets_per_second > dynamic_threshold:
                attack_key = f"volumetric_pps_{features.window_size}"

                if not self._is_in_cooldown(attack_key):
                    self._update_cooldown(attack_key)

                    excess_ratio = features.packets_per_second / dynamic_threshold
                    confidence = min(0.99, 0.5 + (excess_ratio - 1) * 0.2)
                    
                    if excess_ratio > 5:
                        severity = "critical"
                    elif excess_ratio > 2:
                        severity = "high"
                    else:
                        severity = "medium"

                    alert = ThresholdAlert(
                        attack_type=AttackType.PPS_FLOOD,
                        severity=severity,
                        confidence=confidence,
                        timestamp=current_time,
                        window_size=features.window_size,
                        current_value=features.packets_per_second,
                        threshold_value=dynamic_threshold,
                        affected_ips=self._get_top_ip_addresses(features.top_src_ips),
                        details={'detection': 'volumetric_pps', 'excess_ratio': excess_ratio},
                    )
                    self.alert_history.append(alert)
                    return alert
        return None

    def detect_syn_flood(self, features, current_time: float) -> Optional[ThresholdAlert]:
        """Detect SYN flood attacks"""
        if (features.syn_ratio > self.config.syn_flood_syn_ratio and
                features.packets_per_second > self.config.syn_flood_min_rate):

            attack_key = f"syn_flood_{features.window_size}"
            if not self._is_in_cooldown(attack_key):
                self._update_cooldown(attack_key)

                confidence = min(0.95, features.syn_ratio)
                
                alert = ThresholdAlert(
                    attack_type=AttackType.SYN_FLOOD,
                    severity="high",
                    confidence=confidence,
                    timestamp=current_time,
                    window_size=features.window_size,
                    current_value=features.syn_ratio,
                    threshold_value=self.config.syn_flood_syn_ratio,
                    affected_ips=self._get_top_ip_addresses(features.top_dst_ips),
                    details={'detection': 'syn_flood', 'syn_ratio': features.syn_ratio},
                )
                self.alert_history.append(alert)
                return alert
        return None

    def detect_udp_flood(self, features, current_time: float) -> Optional[ThresholdAlert]:
        """Detect UDP flood attacks"""
        if (features.udp_ratio > self.config.udp_flood_ratio and
                features.packets_per_second > self.config.udp_flood_min_rate):

            attack_key = f"udp_flood_{features.window_size}"
            if not self._is_in_cooldown(attack_key):
                self._update_cooldown(attack_key)

                confidence = min(0.9, features.udp_ratio)
                
                alert = ThresholdAlert(
                    attack_type=AttackType.UDP_FLOOD,
                    severity="high",
                    confidence=confidence,
                    timestamp=current_time,
                    window_size=features.window_size,
                    current_value=features.udp_ratio,
                    threshold_value=self.config.udp_flood_ratio,
                    affected_ips=self._get_top_ip_addresses(features.top_dst_ips),
                    details={'detection': 'udp_flood', 'udp_ratio': features.udp_ratio},
                )
                self.alert_history.append(alert)
                return alert
        return None

    def detect_entropy_anomaly(self, features, current_time: float) -> Optional[ThresholdAlert]:
        """Detect low entropy anomalies (potential DDoS)"""
        if features.window_size < self.config.min_window_seconds:
            return None
            
        self.history_entropy.append(features.entropy_src_ip)
        
        if len(self.history_entropy) < 10:
            return None

        baseline = sum(self.history_entropy) / len(self.history_entropy)
        threshold = max(self.config.entropy_src_ip_threshold, baseline - 0.2)
        
        if features.entropy_src_ip >= threshold:
            return None

        attack_key = f"entropy_anomaly_{features.window_size}"
        if self._is_in_cooldown(attack_key):
            return None
            
        self._update_cooldown(attack_key)

        entropy_drop = baseline - features.entropy_src_ip
        confidence = min(0.95, 0.5 + entropy_drop)
        
        severity = "high" if features.entropy_src_ip < 0.2 else "medium"
        
        alert = ThresholdAlert(
            attack_type=AttackType.DISTRIBUTED_ENTROPY,
            severity=severity,
            confidence=confidence,
            timestamp=current_time,
            window_size=features.window_size,
            current_value=features.entropy_src_ip,
            threshold_value=baseline,
            affected_ips=self._get_top_ip_addresses(features.top_src_ips),
            details={'detection': 'entropy_anomaly', 'baseline_entropy': baseline, 'entropy_drop': entropy_drop},
        )
        self.alert_history.append(alert)
        return alert

    def detect(self, features) -> List[ThresholdAlert]:
        """Run all detectors and return list of alerts"""
        current_time = time.time()
        alerts: List[ThresholdAlert] = []

        if features.window_size < self.config.min_window_seconds:
            return alerts

        # Run all detectors
        volumetric_alert = self.detect_volumetric(features, current_time)
        if volumetric_alert:
            alerts.append(volumetric_alert)

        syn_alert = self.detect_syn_flood(features, current_time)
        if syn_alert:
            alerts.append(syn_alert)

        udp_alert = self.detect_udp_flood(features, current_time)
        if udp_alert:
            alerts.append(udp_alert)

        entropy_alert = self.detect_entropy_anomaly(features, current_time)
        if entropy_alert:
            alerts.append(entropy_alert)

        # Log alerts
        for alert in alerts:
            logger.info(f"Threshold detection: {alert.attack_type.value} (confidence={alert.confidence:.2f})")

        return alerts

    def get_alert_history(self, limit: int = 100) -> List[Dict[str, Any]]:
        """Get recent alert history"""
        return [alert.to_dict() for alert in list(self.alert_history)[-limit:]]

    def get_stats(self) -> Dict[str, Any]:
        """Get detector statistics"""
        return {
            'alert_history_size': len(self.alert_history),
            'tracked_ips': len(self.ip_packet_counts),
            'dynamic_thresholds_enabled': self.config.enable_dynamic_thresholds,
        }