"""
Threshold-Based Detector

Detects DDoS attacks using static and dynamic thresholds.
"""

import time
import math
from collections import deque
from enum import Enum
from dataclasses import dataclass, field
from typing import Dict, Any, Optional, List, Tuple, Deque
import logging

logger = logging.getLogger(__name__)


class AttackType(Enum):
    """Types of DDoS attacks that can be detected."""
    NONE = "none"
    SYN_FLOOD = "syn_flood"
    UDP_FLOOD = "udp_flood"
    ICMP_FLOOD = "icmp_flood"
    HTTP_FLOOD = "http_flood"
    PPS_FLOOD = "pps_flood"
    BPS_FLOOD = "bps_flood"
    BANDWIDTH_FLOOD = "bandwidth_flood"
    DISTRIBUTED_ENTROPY = "distributed_entropy"


@dataclass
class ThresholdConfig:
    """Configuration for threshold-based detection."""
    # FIX BUG-24: Default aligned with thresholds.yaml (50 000) and prod.yaml.
    # Old default of 10 000 caused false positives on any deployment that did
    # not explicitly override the value.
    packets_per_second_threshold: int = 50_000
    bytes_per_second_threshold: int = 100_000_000
    flows_per_second_threshold: int = 5_000
    packets_per_second_per_ip: int = 5_000
    connections_per_second_per_ip: int = 1_000
    # FIX BUG-23 / BUG-41: entropy threshold now uses the normalised [0,1]
    # scale that FeatureExtractor produces after fixing BUG-41. Values come
    # in as 0–1; 0 = perfectly concentrated (flood), 1 = perfectly uniform.
    entropy_src_ip_threshold: float = 0.7
    syn_flood_syn_ratio: float = 0.8
    syn_flood_min_rate: int = 5_000
    udp_flood_ratio: float = 0.7
    udp_flood_min_rate: int = 10_000
    icmp_flood_ratio: float = 0.5
    icmp_flood_min_rate: int = 5_000
    enable_dynamic_thresholds: bool = True
    dynamic_window_size: int = 60
    dynamic_threshold_multiplier: float = 3.0
    alert_cooldown_seconds: int = 30
    # FIX BUG-26: Changed default from 5 to 1 so that 1-second windows
    # (used by dev.yaml and thresholds.yaml) are not silently skipped.
    min_window_seconds: int = 1
    max_tracked_ips: int = 100_000


@dataclass
class ThresholdAlert:
    """Alert generated by the threshold detector."""
    attack_type: AttackType
    severity: str
    confidence: float
    timestamp: float
    window_size: int
    current_value: float
    threshold_value: float
    affected_ips: List[str]
    details: Dict[str, Any]

    def to_dict(self) -> Dict[str, Any]:
        return {
            'attack_type': self.attack_type.value,
            'severity': self.severity,
            'confidence': self.confidence,
            'timestamp': self.timestamp,
            'window_size': self.window_size,
            'current_value': self.current_value,
            'threshold_value': self.threshold_value,
            'affected_ips': self.affected_ips[:10],
            'details': self.details,
            'detector': 'threshold',
        }


class ThresholdDetector:
    """Detects DDoS attacks using threshold-based rules."""

    def __init__(self, config: Optional[ThresholdConfig] = None) -> None:
        self.config = config or ThresholdConfig()
        self.history_packets: Deque[float] = deque(maxlen=self.config.dynamic_window_size)
        self.history_bytes: Deque[float] = deque(maxlen=self.config.dynamic_window_size)
        # FIX BUG-22: Separate baseline deque (never contains the current
        # sample) so ongoing attack traffic cannot corrupt the normal baseline.
        self._entropy_baseline: Deque[float] = deque(maxlen=self.config.dynamic_window_size)
        self.last_alert_time: Dict[str, float] = {}
        self.ip_packet_counts: Dict[str, Deque[float]] = {}
        self.alert_history: Deque = deque(maxlen=1_000)
        logger.info("ThresholdDetector initialised")

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _is_in_cooldown(self, attack_key: str) -> bool:
        if attack_key not in self.last_alert_time:
            return False
        return (
            time.time() - self.last_alert_time[attack_key]
            < self.config.alert_cooldown_seconds
        )

    def _update_cooldown(self, attack_key: str) -> None:
        self.last_alert_time[attack_key] = time.time()

    def _get_dynamic_threshold(
        self,
        history: Deque[float],
        default_threshold: float,
        direction: str = "upper",
    ) -> float:
        """Compute a dynamic threshold from history (mean ± k·std)."""
        if not self.config.enable_dynamic_thresholds or len(history) < 10:
            return default_threshold

        values = list(history)
        mean = sum(values) / len(values)
        variance = sum((x - mean) ** 2 for x in values) / len(values)
        std = math.sqrt(variance) if variance > 0 else 0.0

        if direction == "lower":
            dynamic = mean - self.config.dynamic_threshold_multiplier * std
            return max(0.0, min(dynamic, default_threshold))

        dynamic = mean + self.config.dynamic_threshold_multiplier * std
        return max(dynamic, default_threshold)

    def _get_top_ip_addresses(
        self, ip_counts: List[Tuple[str, int]], limit: int = 5
    ) -> List[str]:
        return [ip for ip, _ in ip_counts[:limit]]

    # ------------------------------------------------------------------
    # Individual detectors
    # ------------------------------------------------------------------

    def detect_volumetric(self, features: Any, current_time: float) -> List[ThresholdAlert]:
        """
        Detect volumetric DDoS attacks (high PPS and/or BPS).

        FIX BUG-25: The original method checked PPS only and silently ignored
        BPS (bytes_per_second_threshold was in ThresholdConfig but never used).
        Bandwidth-amplification attacks (e.g. DNS/NTP amplification) can hit
        the BPS threshold while staying under the PPS threshold — they were
        completely undetected.  Both checks now run independently.
        """
        alerts: List[ThresholdAlert] = []

        # Append to shared history BEFORE computing dynamic thresholds.
        self.history_packets.append(features.packets_per_second)
        self.history_bytes.append(features.bytes_per_second)

        # --- PPS check ---
        pps_threshold = self._get_dynamic_threshold(
            self.history_packets, self.config.packets_per_second_threshold, "upper"
        )
        if features.packets_per_second > pps_threshold:
            attack_key = f"volumetric_pps_{features.window_size}"
            if not self._is_in_cooldown(attack_key):
                self._update_cooldown(attack_key)
                excess = features.packets_per_second / pps_threshold
                confidence = min(0.99, 0.5 + (excess - 1) * 0.2)
                severity = "critical" if excess > 5 else "high" if excess > 2 else "medium"
                alert = ThresholdAlert(
                    attack_type=AttackType.PPS_FLOOD,
                    severity=severity,
                    confidence=confidence,
                    timestamp=current_time,
                    window_size=features.window_size,
                    current_value=features.packets_per_second,
                    threshold_value=pps_threshold,
                    affected_ips=self._get_top_ip_addresses(features.top_src_ips),
                    details={'detection': 'volumetric_pps', 'excess_ratio': excess},
                )
                self.alert_history.append(alert)
                alerts.append(alert)

        # --- BPS check (FIX BUG-25) ---
        bps_threshold = self._get_dynamic_threshold(
            self.history_bytes, self.config.bytes_per_second_threshold, "upper"
        )
        if features.bytes_per_second > bps_threshold:
            attack_key = f"volumetric_bps_{features.window_size}"
            if not self._is_in_cooldown(attack_key):
                self._update_cooldown(attack_key)
                excess = features.bytes_per_second / bps_threshold
                confidence = min(0.99, 0.5 + (excess - 1) * 0.2)
                severity = "critical" if excess > 5 else "high" if excess > 2 else "medium"
                alert = ThresholdAlert(
                    attack_type=AttackType.BPS_FLOOD,
                    severity=severity,
                    confidence=confidence,
                    timestamp=current_time,
                    window_size=features.window_size,
                    current_value=features.bytes_per_second,
                    threshold_value=bps_threshold,
                    affected_ips=self._get_top_ip_addresses(features.top_src_ips),
                    details={
                        'detection': 'volumetric_bps',
                        'excess_ratio': excess,
                        'gbps': features.bytes_per_second / 1e9,
                    },
                )
                self.alert_history.append(alert)
                alerts.append(alert)

        return alerts

    def detect_syn_flood(self, features: Any, current_time: float) -> Optional[ThresholdAlert]:
        """Detect SYN flood attacks."""
        if (
            features.syn_ratio > self.config.syn_flood_syn_ratio
            and features.packets_per_second > self.config.syn_flood_min_rate
        ):
            attack_key = f"syn_flood_{features.window_size}"
            if not self._is_in_cooldown(attack_key):
                self._update_cooldown(attack_key)
                alert = ThresholdAlert(
                    attack_type=AttackType.SYN_FLOOD,
                    severity="high",
                    confidence=min(0.95, features.syn_ratio),
                    timestamp=current_time,
                    window_size=features.window_size,
                    current_value=features.syn_ratio,
                    threshold_value=self.config.syn_flood_syn_ratio,
                    affected_ips=self._get_top_ip_addresses(features.top_dst_ips),
                    details={'detection': 'syn_flood', 'syn_ratio': features.syn_ratio},
                )
                self.alert_history.append(alert)
                return alert
        return None

    def detect_udp_flood(self, features: Any, current_time: float) -> Optional[ThresholdAlert]:
        """Detect UDP flood attacks."""
        if (
            features.udp_ratio > self.config.udp_flood_ratio
            and features.packets_per_second > self.config.udp_flood_min_rate
        ):
            attack_key = f"udp_flood_{features.window_size}"
            if not self._is_in_cooldown(attack_key):
                self._update_cooldown(attack_key)
                alert = ThresholdAlert(
                    attack_type=AttackType.UDP_FLOOD,
                    severity="high",
                    confidence=min(0.9, features.udp_ratio),
                    timestamp=current_time,
                    window_size=features.window_size,
                    current_value=features.udp_ratio,
                    threshold_value=self.config.udp_flood_ratio,
                    affected_ips=self._get_top_ip_addresses(features.top_dst_ips),
                    details={'detection': 'udp_flood', 'udp_ratio': features.udp_ratio},
                )
                self.alert_history.append(alert)
                return alert
        return None

    def detect_entropy_anomaly(
        self, features: Any, current_time: float
    ) -> Optional[ThresholdAlert]:
        """
        Detect low source-IP entropy anomalies (potential DDoS).

        FIX BUG-22: The original code appended the current entropy to
        history BEFORE computing the baseline, so ongoing attack traffic
        gradually lowered the baseline and disabled detection.  Now the
        current sample is appended AFTER the baseline is computed, keeping
        the baseline anchored to pre-attack normal traffic.

        FIX BUG-23 / BUG-41: Entropy values arriving here are already
        normalised to [0,1] by FeatureExtractor._normalise_entropy().  The
        config threshold (0.7) and the dynamic-threshold arithmetic both
        operate on the same [0,1] scale, so comparisons are now meaningful.
        Previously, raw Shannon-bit values (~2–5) were always ≥ 0.7, making
        the early-return guard fire unconditionally and entropy detection
        permanently disabled.
        """
        if features.window_size < self.config.min_window_seconds:
            return None

        # FIX BUG-22: compute baseline from HISTORY only (exclude current sample).
        if len(self._entropy_baseline) < 10:
            # Not enough history yet — update history and skip detection.
            self._entropy_baseline.append(features.entropy_src_ip)
            return None

        baseline = sum(self._entropy_baseline) / len(self._entropy_baseline)

        # Dynamic lower threshold: take the stricter of config value and
        # (baseline - 0.2).  This adapts to the observed normal entropy level.
        threshold = max(self.config.entropy_src_ip_threshold, baseline - 0.2)

        # FIX BUG-22 (cont.): Append AFTER computing baseline.
        self._entropy_baseline.append(features.entropy_src_ip)

        if features.entropy_src_ip >= threshold:
            return None

        attack_key = f"entropy_anomaly_{features.window_size}"
        if self._is_in_cooldown(attack_key):
            return None

        self._update_cooldown(attack_key)

        entropy_drop = baseline - features.entropy_src_ip
        confidence = min(0.95, 0.5 + entropy_drop)
        severity = "high" if features.entropy_src_ip < 0.2 else "medium"

        alert = ThresholdAlert(
            attack_type=AttackType.DISTRIBUTED_ENTROPY,
            severity=severity,
            confidence=confidence,
            timestamp=current_time,
            window_size=features.window_size,
            current_value=features.entropy_src_ip,
            threshold_value=baseline,
            affected_ips=self._get_top_ip_addresses(features.top_src_ips),
            details={
                'detection': 'entropy_anomaly',
                'baseline_entropy': baseline,
                'entropy_drop': entropy_drop,
            },
        )
        self.alert_history.append(alert)
        return alert

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def detect(self, features: Any) -> List[ThresholdAlert]:
        """
        Run all sub-detectors and return the combined list of alerts.

        FIX BUG-26: min_window_seconds default changed from 5 → 1 in
        ThresholdConfig, so 1-second windows are no longer silently
        discarded.  The guard is kept for safety; callers can still
        configure a higher minimum if desired.
        """
        current_time = time.time()
        alerts: List[ThresholdAlert] = []

        if features.window_size < self.config.min_window_seconds:
            return alerts

        # FIX BUG-25: detect_volumetric now returns a list (PPS + BPS).
        volumetric_alerts = self.detect_volumetric(features, current_time)
        alerts.extend(volumetric_alerts)

        syn_alert = self.detect_syn_flood(features, current_time)
        if syn_alert:
            alerts.append(syn_alert)

        udp_alert = self.detect_udp_flood(features, current_time)
        if udp_alert:
            alerts.append(udp_alert)

        entropy_alert = self.detect_entropy_anomaly(features, current_time)
        if entropy_alert:
            alerts.append(entropy_alert)

        for alert in alerts:
            logger.info(
                f"Threshold alert: {alert.attack_type.value} "
                f"(confidence={alert.confidence:.2f}, severity={alert.severity})"
            )

        return alerts

    def get_alert_history(self, limit: int = 100) -> List[Dict[str, Any]]:
        return [a.to_dict() for a in list(self.alert_history)[-limit:]]

    def get_stats(self) -> Dict[str, Any]:
        return {
            'alert_history_size': len(self.alert_history),
            'tracked_ips': len(self.ip_packet_counts),
            'dynamic_thresholds_enabled': self.config.enable_dynamic_thresholds,
        }